# Generated by Django 6.0 on 2026-01-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(help_text='Unique card ID (e.g., C1001)', max_length=50)),
                ('door_name', models.CharField(help_text='Door name (e.g., Main Entrance)', max_length=100)),
                ('access_granted', models.BooleanField(default=True, help_text='Access granted (True) or denied (False)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Time when the event occurred')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time when the database entry was created')),
            ],
            options={
                'verbose_name': 'Access Log',
                'verbose_name_plural': 'Access Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['card_id'], name='access_cont_card_id_714450_idx'), models.Index(fields=['-timestamp'], name='access_cont_timesta_7f246a_idx')],
            },
        ),
    ]
